# -*- coding: utf-8 -*-
"""loops&functions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bsg7SDy-ngckg-a1OnlxEgb4qDH8YBDF
"""

def greet(username):
  print(f"Hello, {username}! Kese ho ?")

def count_to_number(number):
  for i in range(1, number + 1):
    print(i)

user_name = input("Enter your name: ")
greet(user_name)

count_to = int(input("Enter a number to count to: "))
count_to_number(count_to)

